### ISSUE TITLE
Disallow "... = ... or ..." in lua

### ISSUE THREAD

**Issue by grafin** [tarantool/luacheck#17]
Because of `box.NULL` being equal to `nill` but not being equal to `false` usual lua constructions like `opts = opts or {}` can lead to problems like https://github.com/tarantool/tdg2/issues/1546. After we fix [all current similar problems](https://github.com/tarantool/tdg2/issues/1825) it would be great, if we could automatically prevent new ones.

Moved from https://github.com/tarantool/checkpatch/issues/52

**Comment by Totktonada** [comment]
So how optional arguments handling would look like? For example, the following snippet.

```lua
local function foo(a, b, opts)
    assert(a ~= nil)
    assert(b ~= nil)
    local opts = opts or {}
    local c = opts.c or 10
    local d = opts.d or 'info'
    <...>
end
```

**Comment by grafin** [comment]
Because `box.NULL == nil` we can replace the code with `if opts == nil then opts = {} end`.

If it is possible we can only disallow it for function arguments, and still allow it for local vars, which we can be sure are not equal to `box.NULL`.
```lua
local function foo(a, b, opts)
    assert(a ~= nil)
    assert(b ~= nil)
    if opts == nil then opts = {} end -- This one is pretty straight-forward

    local c = opts.c
    if c == nil then c = 10 end
 
    local d = opts.d
    if d == nil then
        d = 'info'
    end
    <...>
end
```

[Currently we have to rewrite the shorter `local c = opts.c or 10` variant with the longer one anyway...](https://github.com/tarantool/tdg2/commit/98b113eb4a4f71f26a34f2522e6a93ed4e67db90)

**Comment by kyukhin** [comment]
I don't think we're about to do that, sorry.

**Comment by igormunkin** [comment]
My two cents about this problem:
1. Your (and everyone's else) problem doesn't relate to `or` usage, but comes from `box.NULL` usage. It's poorly designed thing in LuaJIT, but the worst thing, that this value is widely used in Tarantool. I can only suggest to use this as little as possible.
2. *Nice* linters (such as checkpatch.pl) provide several "error levels". I can agree, that we can introduce so called warning level to add hints for users when they're doing something fishy (e.g. using `box.NULL`).

Implementing the taboo for using the widely used idiom due to misuse of the misdesigned FFI features is a total nonsense to me.

**Comment by Totktonada** [comment]
Igor,

This is non-sense recommendation for tarantool users (module/app developers), because the box.NULL of the question comes from a tarantool's own msgpack deserializer. All other deserializers do the same (json/yaml).

If your suggestion is for tarantool developers, it sounds like 'don't solve problems'. If you want to drive it toward some decisions, the reasons of box.NULL introduction (represent JSON's `null`?) should be analyzed and alternatives should be proposed.

Now it sounds pathetic and non-practical. I mean, "don't use X" -- "but it solves problem Y" -- "I don't give a fuck".

**Comment by igormunkin** [comment]
Sasha,

At first, I believe, it's worth adding disclaimer regarding my previous comment: the first bullet is only my own opinion, that hasn't been changed for 3 last years; it's not the recommendation.

> This is non-sense recommendation for tarantool users (module/app developers), because the box.NULL of the question comes from a tarantool's own msgpack deserializer. All other deserializers do the same (json/yaml).

Using `box.NULL` widely in Tarantool doesn't make it properly designed. I consider converting `nil` to `box.NULL` via our serializers as a bug. Furthermore, I see no reason why `box.NULL` should be equal to `nil`, hence, it might be implemented in any other way except `ffi.new('void *')`.

> If your suggestion is for tarantool developers, it sounds like 'don't solve problems'. If you want to drive it toward some decisions, the reasons of box.NULL introduction (represent JSON's `null`?) should be analyzed and alternatives should be proposed.

Precisely. And I suggest to move it to the relevant thread.

> 
> Now it sounds pathetic and non-practical. I mean, "don't use X" -- "but it solves problem Y" -- "I don't give a fuck".

Here we comes to the second bullet and your words above are not quite right:
* Of course, I don't expect Tarantool stop using FFI for that (at least I found no support for this at the moment).
* Of course, if user can't read about FFI (and ergo `box.NULL`) semantics, I don't give a fuck.
* Once more, I'm still *for* improving our linting tools to prevent users from mistakes, but I totally don't like proposals saying "forbid widely used Lua idiom".

**Comment by igormunkin** [comment]
And yes, before banning something, it's definitely worth to add a convenient tool for processing defaults (instead of using hacks with boolean operators): a special function considering all Tarantool specifics is a nice alternative IMHO.

And `luacheck` can suggest using this function instead of the aforementioned constructions.
